### ISSUE TITLE
Feature extensions for local file tagging of lyrics 

### ISSUE THREAD

**Issue by iconoclasthero** [Jugran/lyrics-in-terminal#40] opened 2024-05-31 00:16 UTC
So, off the bat, if you can display the link to the lyrics source URL, then you have a clickable link (at least in a lot of terminals I think) where someone could go and double check the lyrics if need be and there's no real solid reason why you couldn't use one of the mutagen or whatever libraries from musicbrainz to write the lyrics to the metadata.  I mean otherwise what, really, is the point of editing the lyrics other than to correct them before saving them to metadata tags.

Anyway, i've got some ideas for moving this along...  I'm going to fork it so if you ever get back to this project, lemme know.

**Comment by Jugran** [comment] 2024-08-20 18:25
Duplicate of #30

**Closed as not planned** 2024-08-20 18:26 UTC
